### ISSUE TITLE
Sonarr and Authelia - Container error 'The address already exists'

### ISSUE THREAD

**Issue by townsmcp** [doob187/traefikv2apps#26]
I noticed that a lot of my containers would shut down over night. When trying to start the container the next day I would get an error message stating 'The address already exists'.
I noticed Sonarr and Authetlia containers both had an IPv4 address set (172.18.0.4 for Sonarr and 172.18.0.8 for Authelia). I have removed both of these addresses in Portainer and both start up fine now. Also, since rmeoving the hard coding of the IP none of the containers have been stopping overnight. Just thought I would report his in case anyone else sees similar behaviour

**Comment by doob187** [comment]
basicly docker-compose give the docker one IP [ see screen below ];

so the problem is .. when now .. the docker stoppend [ miss pulling / stop / error / iss updated or any other cases ] the container cant use the same IP again [ the docker service gives another container this IP {{ since ist avaible }} ]

so i dont notice yet,, but i could see/check what i can do tp bypass this once 

when you remove th given IP [[ fdocker IP before ]] then it will use the next avaible IP [[ local IP mask ]]

@mrfret  [[ i add you now to this issuse ]] 

![image](https://user-images.githubusercontent.com/60312740/115586849-484e0480-a2cd-11eb-9f0a-7dc48a06636a.png)
